global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'pipeline'
    metrics_path: /
    static_configs:
      - targets: ['pipeline:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]